### ISSUE TITLE
Handling .MP files and other improvements

### ISSUE THREAD

**Issue by erkexzcx** [simulot/immich-go#106]
immich-go (latest release) says this:

```
96 files can't be handled
File: Takeout/Google Photos/Photos from 2022/PXL_20221023_154403118.MP
        File type not supported
...
File: Takeout/Google Photos/Photos from 2022/PXL_20221130_133152467.MP~2
        File type not supported
...
File: Takeout/Google Photos/Trash/PXL_20231002_094557549.MP
        File type not supported
File: Takeout/archive_browser.html
        File type not supported
Done.
```

There is something that needs to be fixed:

1. `.MP` files need to have `.mp4` extension added. [Google messed up, therefore it's missing](https://support.google.com/photos/thread/139943915/open-or-convert-mp-file?hl=en). All those `.MP.mp4` open as short video and work perfectly in VLC. I assume this is video for "motion pictures"?

Example how it looks like in my .zip file:
![image](https://github.com/simulot/immich-go/assets/5955795/2de68a26-3547-4f98-8832-4100df30ad82)

2. `Takeout/Google Photos/Trash/` - does it mean that immich-go "restores" photos from trash back to Immich? Well, I do believe this is not something a typical user would expect. Is it possible to restore directly to Immich trash?
3. Some random files need to be blocklisted, such as `File: Takeout/archive_browser.html`
4. I am not sure how such file `PXL_20221130_133152467.MP~2` ended up in google photos and no idea how to handle it. Nothing to suggest, so I'd leave it to you to decide.

Btw your app is AWESOME! :slightly_smiling_face:

**Comment by simulot** [comment]
Thanks for your nice comment.

**Mp files**

Mp files are not supported by immich.

Their content is embedded into the file .mp.jpg file and immich recognize them as live photo. So they are ignored by design.




**Trashed files**

They are ignored by immich-go by default. There is a flag to reverse this. Then files will be uploaded as regular images, at the time of writing the program, immich didn't support it.

So why not.


**HTML files**
This file is provided by Google to let you navigate in the takeout archive. You can disregard it.

In a future version, I'll report them as useless files, like mp files 

**PXL_20221130_133152467.MP~2**

It should have a Json an a mp file in the takeout, maybe in another part of the zip.

You can extract the mp.jpg file and drop it on the immich web page.

I can investigate the case if you provide the names of related files

**Comment by coldfusion571** [comment]
immich-go appears to successfully have handled a bunch of .MP.jpg files, however it failed to handle the files with extension .MP

What's the difference here?  I also do see a bunch of photos in immich, that have a play button and show a short video when pressed.. much like google photos.

---

I think I found a partial answer to this,

[mp.jpg vs mp](https://support.google.com/pixelphone/thread/171080138/mp-sidecar-files-to-mp-jpg-files-what-do-to-with-them?hl=en)

But then I'm wondering, are the .MP files superfluous?  Duplicates of what's stored in the .MP.jpg?

**Comment by simulot** [comment]
The mp file is embedded into the .mp.jpg 
the immich server use the embedded content to import the movie associated with the photo. So, it's better to not import it.
