### ISSUE TITLE
Duplicate command: Option to keep smaller photos

### ISSUE THREAD

**Issue by muety** [simulot/immich-go#378]
In Google Photos, I tend to apply the "Optimize" filter to every image, resulting in a duplicate with the exact same name and creation date. Google Photos silently "hides" the original photo and only shows the edited one in the app, but apparently still keeps the original version. When exporting to Immich, both variants are imported, while I usually only want to keep the edited one.

I don't think there is a good way to distinguish both versions. The only difference that I noticed is that the edited photos is almost always _smaller_ in file size. Immich's `duplicate` command properly detects all those duplicates, but only offers to keep the _larger_ one.

I'd like to have a flag to instruct the command to delete duplicates based on file size, either smaller or larger.

**Comment by simulot** [comment]
That is interesting... 

The duplicate functionality has been build to clean the duplication due to the storage in immich of the original files and the import of google takeout archive of more compressed files. 

I can imagine that an user's photo collection is a mix between edited photos and takeout duplicates... In this case, a simple option would either eliminate the "best quality" photo or the edited version.

With my own phone, I get the original photos and the corrected photos with -edited suffix.  The duplicate command is based on the file name, therefore the -edited photo isn't removed.

Have you checked the immich's "review duplicate" functionality?

**Comment by muety** [comment]
Thanks for the quick reply! Immich's "Review Duplicates" does not detect any duplicates. The issue might also be related to the takeoout or to my photo collection itself, rather than immich-go. But perhaps somebody can still help me "debug" this.

There are the metadata of the two images, whereas the 724.6 KiB one is clearly the edited version:

<img src="https://github.com/user-attachments/assets/fb3f970d-3c89-43ed-933a-2a9e9759667c" width="200px">

<img src="https://github.com/user-attachments/assets/a8251a7d-5522-4557-bde6-47ee767d0ff7" width="200px">

And here are the contents of my takeout:

```bash
$ unzip -l takeout-20240714T125444Z-001.zip | grep 6199cce3-8a55 | less

  1048555  07-14-2024 15:05   Takeout/Google Fotos/Some Album/original_6199cce3-8a55-42b0-bdd0-10b71e0802a8_P.jpg
      838  07-14-2024 15:05   Takeout/Google Fotos/Some Album/original_6199cce3-8a55-42b0-bdd0-10b71e0802a8_.json
   741954  07-14-2024 15:05   Takeout/Google Fotos/Some Album/original_6199cce3-8a55-42b0-bdd0-10b71e0802a8_P(1).jpg
   741954  07-14-2024 15:23   Takeout/Google Fotos/Photos from 2024/original_6199cce3-8a55-42b0-bdd0-10b71e0802a8_P(1).jpg
  1048555  07-14-2024 15:23   Takeout/Google Fotos/Photos from 2024/original_6199cce3-8a55-42b0-bdd0-10b71e0802a8_P.jpg
      837  07-14-2024 15:23   Takeout/Google Fotos/Photos from 2024/original_6199cce3-8a55-42b0-bdd0-10b71e0802a8_.json

**Comment by muety** [comment]
What do you think? Any thoughts on this?

**Comment by simulot** [comment]
I'm not convinced this can work for most of the users.

**Comment by muety** [comment]
Alright, no worries, I'll probably write some scripts for myself to achieve the above.
